// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ectmpndxvapuumlmxvku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjdG1wbmR4dmFwdXVtbG14dmt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NjU3NTcsImV4cCI6MjA2OTE0MTc1N30.adT6hJdpIE356e74LL6qWK4qzqhEy3BiOWMtvb054Io";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});